name: 'On Pushed'

on:
  workflow_call

jobs:
  call_build_test_upload:
    uses: ./.github/workflows/workflow_call_push.yml
    with:
      artifact_name: 'app'
      is_pullrequest: 'false'

  call_deploy_fncapp:
    uses: ./.github/workflows/workflow_call_deploy_fncapp.yml
    needs:
    - call_build_test_upload
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      artifact_name: 'app'

  call_deploy_sttapp:
    uses: ./.github/workflows/workflow_call_deploy_sttapp.yml
    needs:
    - call_build_test_upload
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    with:
      artifact_name: 'app'
