name: Deploy SWA to Azure

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: false
        description: Artifact name
        default: 'app'

env:
  AZURE_RESOURCE_GROUP_NAME: 'rg-${{ secrets.AZURE_ENV_NAME }}'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_APIM_NAME: 'apim-${{ secrets.AZURE_ENV_NAME }}'
      AZURE_STTAPP_NAME: 'sttapp-${{ secrets.AZURE_ENV_NAME }}'

    steps:
    - name: Download Function app artifact
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/published

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Get APIM endpoint
    #   shell: bash
    #   run: |
    #     subscription_id=$(az account show --query "id" -o tsv)

    #     gateway_url=$(az apim show -g $AZURE_RESOURCE_GROUP_NAME -n $AZURE_APIM_NAME --query "gatewayUrl" -o tsv)
    #     apim_endpoint=$gateway_url/kakao/access-token

    #     echo "::add-mask::$apim_endpoint"
    #     echo "APIM_ENDPOINT=$apim_endpoint" >> $GITHUB_ENV

    - name: Get SWA token
      shell: bash
      run: |
        swa_token=$(az staticwebapp secrets list -g $AZURE_RESOURCE_GROUP_NAME -n $AZURE_STTAPP_NAME --query "properties.apiKey" -o tsv)

        echo "::add-mask::$swa_token"
        echo "SWA_TOKEN=$swa_token" >> $GITHUB_ENV

    - name: Update appsettings.json
      shell: pwsh
      run: |
        pushd ${{ github.workspace }}/published/${{ inputs.artifact_name }}-web/wwwroot

        $(Get-Content -Path ./appsettings.sample.json -Raw) -replace "<AZURE_APIM_NAME>", "${{ env.AZURE_APIM_NAME }}" | `
          ConvertFrom-Json | ConvertTo-Json -Depth 10 | `
          Out-File -Path ./appsettings.json -Force

        popd

    # - name: Deploy SWA to Azure
    #   shell: bash
    #   run: |
    #     swa deploy -d ${{ env.SWA_TOKEN }} -a ${{ github.workspace }}/published/${{ inputs.artifact_name }}-web/wwwroot --env default

    - name: Deploy SWA to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        skip_app_build: true
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "${{ github.workspace }}/published/${{ inputs.artifact_name }}-web/wwwroot" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######